import random
import secrets

# Get a random float from zero to one
random.random()  # returns a random float between 0, 1

# Get random float from a custom range
random.uniform(2, 5)

# Get random int from a custom range
random.randint(3, 6)  # includes the upper bound
random.randrange(3, 7)  # Does not include the upper bound

# Return a random elelment from a list
mylist = list("THELISTISGOOD")
# Get a single element from the list
print(random.choice(mylist))
# Get an arbitrary number of random elements from the list
print(random.sample(mylist, 3))


# Using the secrets module for more security
# Since the values generated by the random module can be replicated using the seed function
secrets.randbelow(
    4
)  # produces any random number in the range from 0 to 4 and 4 is not included
a = secrets.randbits(3)
print(a)

a = secrets.choice(mylist)
print(a)
